# Site
repository: kghorvath/kghorvath.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Kamin Horvath
title: Business Development Manager
email: kamin@kghorvath.com
website: https://kghorvath.com

darkmode: true 

# Social links
github_username: kghorvath
linkedin_username: khorvath
# Additional icon links
additional_links:
- title: Mastodon
  icon: fa-mastodon
  url: https://social.gatorarms.net/@mohaas
- title: Keyoxide 
  icon: fas fa-key
  url: https://keyoxide.org/690B23AB88DB51FF9DE715AEF1D143CB0E1ECCF6
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-8945456-6"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/38924930.jpg
about_content: | # this will include new lines to allow paragraphs
 Hello, my name is Kamin Horvath. I am an business development manager working in the mechanical contracting industry. I specialize in direct for owner sales of mechanical projects and maintenance.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
more_content: | # this will include new lines to allow paragraphs
 Aside from my roles as a sales assistant and IT outreach, I also like to work with technology and networking in my space time. Some of my personal projects include

   - Running a home server lab. I'm interested in retrocomputing and home networking, and host a number of services including my personal webpage, and a Mastodon instance.
   - Building and running this website. I host this site on my personal repository on GitHub Pages, built with jekyll using the wonderful [modern resume theme.](https://github.com/sproogen/modern-resume-theme)
   - Retro computing. I enjoy building and tinkering with older computers and software.



# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
