# Site
repository: kghorvath/kghorvath.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Kamin Horvath
title: Business Development Manager
email: kamin@kghorvath.com
website: https://www.kghorvath.com

darkmode: true 

# Social links
github_username: kghorvath
linkedin_username: khorvath
# Additional icon links
additional_links:
- title: Mastodon
  icon: fab fa-mastodon
  url: https://social.kghorvath.com/@kamin
- title: Keyoxide 
  icon: fas fa-key
  url: https://keyoxide.org/7270B1E4CCFF3889F0DE56576AD93F1D3F3ACCCC
- title: Resume
  icon: fas fa-file-alt
  url: https://github.com/kghorvath/kghorvath.github.io/blob/47a79545b0b7cddcc53c97e074957faafbd5818e/assets/Kamin_Horvath_Resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-8945456-6"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/38924930.jpg
about_content: | # this will include new lines to allow paragraphs
 Hello, my name is Kamin Horvath. I am an business development manager working in the mechanical contracting industry. I specialize in direct for owner sales of mechanical projects and maintenance.

content:
- title: Experience # Title for the section
  layout: list # Type of content section (list/text)
  content:
    - layout: left
      title: ABM
      link: abm.com
      sub_title: Business Development Manager
      caption: February 2022 - Present
      description: |
        I currently work for ABM Technical Solutions in Alpharetta, GA. My primary role is driving and developing HVAC project and maintenance sales to commercial and industrial end users. I also work to help sell other ABM lines such as arc flash testing, EV charging, and janitorial services.
   
    - layout: left
      title: Maxair Mechanical
      link: maxairmech.com
      sub_title: Assistant Project Manager
      caption: February 2020 - February 2022
      description: |
        I worked as an assistant project manager for Maxair, a mechanical contractor operating in Georgia, for the Direct for Owner (DFO) projects team, specializing in selling directly to property owners and managers. Responsibilites range from sales of individual equipment replacements, to developing full capital plans for ongoing work.

    - layout: left
      title: James M. Pleasants Co.
      link: jmpco.com
      sub_title: Technical Engineering Sales Support
      caption: May 2015 - February 2020
      description: |
        I started at this company as an inside sales representative, providing pricing on replacement parts and equipment to our customers. I was promoted to this position as a technical resource for the outside sales team in our Georgia branch. I assist our salesmen as well as some of the engineers we work with in designing systems along with the equipment to go along with it. I also assemble project quotes and submittals for our contractor and wholesale customers.

- title: Education
  layout: list
  content:
    - layout: left
      title: Virginia Tech
      caption: 2011 - 2015
      sub_title: B.Sc., Mechanical Engineering
      description: |
        I studied for 4 years at Virginia Tech, earning my bachelor's degree in Mechanical Engineering. I'm proud of our senior project, which was to design and prototype a portable dental chair small enough to be carried onto a commercial flight, yet stable and sturdy enough to withstand use in underdeveloped areas and accomodate a wide range of body shapes and sizes. Our design was a success and in fact, has been put into use by the outreach dentistry program at the University at Buffalo. 

- title: Projects
  layout: text
  content: |
    Aside from my roles as a sales assistant and IT outreach, I also like to work with technology and networking in my space time. Some of my personal projects include
    - Running a home server lab. I'm interested in retrocomputing and home networking, and host a number of services including my personal webpage, and a Mastodon instance. I also host this very site on my personal repository on GitHub Pages, built using the wonderful [modern resume theme.](https://github.com/sproogen/modern-resume-theme)
    - Retro computing. I enjoy building and tinkering with older computers and software.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
